---
title: 'How is catching Rust FFI panic possible?'
date: 2023-01-30
permalink: /posts/2023/01/bp1/
tags:
  - FFI
  - foreign exception
---

How is it possible for C++ to catch panic from Rust function? Is it an intended behavior? Let me show it and prove it with details of source implementation!

Catching foreign exception
======

Sample code of Rust/C++
------
The code works on macOS.  
After we build the dynamic-linked library of Rust, we can try to search
```
// given the command `nm liboob.dylib| grep ' T '`
0000000000021d5c T ___rust_start_panic
0000000000002348 T _oob
000000000001b93c T _rust_begin_unwind
000000000001d87c T _rust_eh_personality
000000000001af40 T _rust_oom
000000000001bf10 T _rust_panic
```

Reference
======
Thanks for the guide of [Using Unsafe for Fun and Profit](https://michael-f-bryan.github.io/rust-ffi-guide/overview.html)